development:
  adapter: postgresql
  encoding: utf8
  database: pattern_dev
  pool: 5
  username: 
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: pattern_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: pattern_prod
  pool: 5
  username: 
  password:

cucumber:
  <<: *TEST
